"""LangGraph agent state definition."""

from __future__ import annotations

import uuid
from typing import TypedDict


class ProductCandidate(TypedDict):
    product_id: str
    title: str
    brand: str | None
    price_cents: int
    tags: list[str]
    image_url: str | None
    score: float  # vector similarity score


class RecommendationResult(TypedDict):
    product_id: str
    score: float  # agent ranking score 0-1
    reason: str  # explanation in user's language


class AgentState(TypedDict):
    # Input
    user_id: str
    occasion: str | None  # optional: "travail", "soiree", "casual", "plage"
    mood: str | None  # optional: "classique", "tendance", "decontracte"

    # Context (filled by gather_context)
    user_profile: dict  # gender, style_tags, budget, favorite_colors, etc.
    weather: dict | None  # temperature, conditions, season
    trends: list[str]  # trending tags for current season

    # Search planning (filled by plan_search)
    search_queries: list[str]  # 2-4 search queries generated by LLM

    # Search results (filled by execute_search)
    candidate_products: list[ProductCandidate]

    # Final output (filled by rank_and_filter + format_output)
    recommendations: list[RecommendationResult]
    agent_run_id: str
